### ISSUE TITLE
The cypress-mock-openapi is exactly what I needed

### ISSUE THREAD

**Issue by haggen** [heetch/frontend-tools#2]
Hi, I've been working on a very similar solution but now that I found yours I'm tempted to use it, though it needs a few updates.

Is it still being maintained? Would a PR be welcome for this package?

I ask because the the CORS issue mentioned in the code, for instance, has been fixed several versions ago.

Thanks in advance.

**Comment by tamarasaurus** [comment]
Hey @haggen thanks for your interest :slightly_smiling_face: we still maintain this project so a PR would be more than welcome. Indeed we could update Cypress to clean up this CORS fix - what other updates were you thinking of?

**Comment by haggen** [comment]
Hi Tamara, thanks for the reply!

I was thinking mostly of updating the dependencies (cypress version, for instance) and take advantage of any fixes or improvements (such as the CORS issue). 

But as I was implementing this solution I realized I can't intercept and modify the response, AFAIK. That was a deal breaker for me cause I'm using the API mock to validate the app's behavior against regular data and then against variations (such as multiple items in an array, different user status, etc).

For now I thought I would stick to the actual discrete server prism-cli offers and I'm using cy.intercept to handle the variations.

In any case the project looks very interesting and I'll keep an eye on ti.

Thanks again and a nice one! :beers:
